const $=id=>document.getElementById(id);
const fmt=n=>new Intl.NumberFormat("en-US",{maximumFractionDigits:0}).format(n);
const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(n);
function seed(i){const x=Math.sin(i*91.17+17.3)*43758.5453;return x-Math.floor(x)}
const effects=[-0.2,-0.1,0.0,0.1,0.0,0.2,0.4,0.7,1.0,1.3,1.6,1.9,2.0,2.1,2.0,2.2,2.3,2.4,2.35];
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.tab-panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")});
function renderEvent(){const el=$("eventChart");el.innerHTML="";effects.forEach((v,i)=>{const p=document.createElement("i");p.style.left=(i/(effects.length-1)*96+2)+"%";p.style.bottom=(50+v*10)+"%";p.title=(i-6)+" days: "+v.toFixed(1)+" pp";el.appendChild(p)})}
function evalPrompt(){const strict=Number($("judgeStrict").value);$("judgeOut").textContent=strict+"%";const v=$("promptVersion").selectedIndex;const base=[92.4,89.7,91.2,94.1,3.8,95.0];const shifts=[[0,0,0,0,0,0],[1.2,1.5,1.0,.7,-.8,1.1],[2.1,2.0,1.7,1.8,-1.3,1.8],[2.6,2.7,2.1,2.2,-1.8,2.2]][v];$("faith").textContent=(base[0]+shifts[0]-(strict-90)*.02).toFixed(1)+"%";$("relevance").textContent=(base[1]+shifts[1]).toFixed(1)+"%";$("complete").textContent=(base[2]+shifts[2]).toFixed(1)+"%";$("citation").textContent=(base[3]+shifts[3]).toFixed(1)+"%";$("halluc").textContent=Math.max(1.4,base[4]+shifts[4]+(100-strict)*.03).toFixed(1)+"%";$("instruction").textContent=(base[5]+shifts[5]).toFixed(1)+"%"}
$("judgeStrict").oninput=evalPrompt;$("promptVersion").onchange=evalPrompt;$("runEval").onclick=evalPrompt;
function causal(){const e=$("estimator").value;$("estimatorLabel").textContent=e;renderEvent()}
$("runCausal").onclick=causal;
const costs=[.10,.15,.21,.30,.40,.50,.75,1.00],values=[1.31,1.26,1.18,1.10,.98,.84,.61,.34];
$("costSensitivity").innerHTML=costs.map((c,i)=>'<div class="bars"><div><span>'+money(c)+'/resolution</span><b style="width:'+Math.round(values[i]/1.31*100)+'%"></b><em>'+money(values[i])+'</em></div></div>').join("");
function policy(){const budget=Number($("trafficBudget").value),effect=Number($("minEffect").value);$("trafficOut").textContent=budget+"%";$("effectOut").textContent=effect.toFixed(1)+" pp";const share=Math.max(0,Math.min(budget,Math.round(74-effect*5)));const value=1.22*(share/68);$("routeShare").textContent=share+"%";$("routeValue").textContent="$"+value.toFixed(2)+"M";$("routeRule").textContent="Route if expected incremental contribution − AI cost > 0 and CATE ≥ "+effect.toFixed(1)+" pp, subject to latency and traffic constraints."; $("routeCostValue").textContent="$"+(0.36*share/68).toFixed(2)+"M";$("economicCoverage").textContent=share+"%"}
$("trafficBudget").oninput=policy;$("minEffect").oninput=policy;renderEvent();policy();evalPrompt();

const evalCases={
faithfulness:{title:"Faithfulness · trace #184",query:"What refund window applies to this customer?",context:"Policy KB §4.2: refunds are eligible within 30 days for qualifying purchases.",answer:"The customer can request a refund within 30 days.",verdict:"PASS",rationale:"The substantive claim is directly supported by the retrieved policy paragraph.",meta:"judge 0.97 · human 1 · citation span 4.2"},
citation:{title:"Citation correctness · trace #071",query:"Which plan includes priority support?",context:"Pricing KB §2.1: Pro includes priority support; Basic does not.",answer:"Priority support is included with Pro. [Pricing KB §2.1]",verdict:"PASS",rationale:"The cited source contains the exact product attribute asserted by the answer.",meta:"judge 0.95 · human 1 · claim-to-source match"},
completeness:{title:"Completeness · trace #132",query:"Summarize the cancellation policy and tell me what happens to unused credits.",context:"Cancellation KB §3.1: cancellation stops renewal. §3.4: unused credits expire at the end of the billing period.",answer:"You can cancel at any time and renewal will stop.",verdict:"PARTIAL",rationale:"The answer is faithful but omits the required consequence for unused credits. This is a completeness failure, not a hallucination.",meta:"judge 0.88 · human 0 · missing required fact: §3.4"},
hallucination:{title:"Unsupported inference · trace #209",query:"Will cancelling today refund the current month?",context:"Cancellation KB §3.1: cancellation stops renewal. No refund rule is stated in the retrieved context.",answer:"Yes, cancelling today will automatically refund the current month.",verdict:"FAIL",rationale:"The response introduces a refund claim that is absent from the retrieved evidence. The system should abstain or retrieve the refund policy.",meta:"judge 0.99 · human 0 · unsupported claim detected"}
};
function renderEvalCase(key="faithfulness"){const d=evalCases[key],el=$("evalCase");if(!el)return;el.innerHTML='<div class="case-title"><div><small>'+d.verdict+'</small><h4>'+d.title+'</h4></div><span>'+d.meta+'</span></div><div class="case-columns"><div><small>USER QUERY</small><p>'+d.query+'</p><small>RETRIEVED EVIDENCE</small><blockquote>'+d.context+'</blockquote></div><div><small>MODEL RESPONSE</small><p>'+d.answer+'</p><small>EVALUATION</small><div class="verdict '+d.verdict.toLowerCase()+'"><b>'+d.verdict+'</b><span>'+d.rationale+'</span></div></div></div>'}
document.querySelectorAll(".case-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".case-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderEvalCase(b.dataset.case)});
renderEvalCase();
