const $=id=>document.getElementById(id);
const fmt=n=>new Intl.NumberFormat("en-US",{maximumFractionDigits:0}).format(n);
const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(n);
function seed(i){const x=Math.sin(i*91.17+17.3)*43758.5453;return x-Math.floor(x)}
const effects=[-0.2,-0.1,0.0,0.1,0.0,0.2,0.4,0.7,1.0,1.3,1.6,1.9,2.0,2.1,2.0,2.2,2.3,2.4,2.35];
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.tab-panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")});
function renderEvent(){const el=$("eventChart");el.innerHTML="";effects.forEach((v,i)=>{const p=document.createElement("i");p.style.left=(i/(effects.length-1)*96+2)+"%";p.style.bottom=(50+v*10)+"%";p.title=(i-6)+" days: "+v.toFixed(1)+" pp";el.appendChild(p)})}
function evalPrompt(){const strict=Number($("judgeStrict").value);$("judgeOut").textContent=strict+"%";const v=$("promptVersion").selectedIndex;const base=[92.4,89.7,94.1,3.8];const shifts=[[0,0,0,0],[1.2,1.5,.7,-.8],[2.1,2.0,1.8,-1.3],[2.6,2.7,2.2,-1.8]][v];$("faith").textContent=(base[0]+shifts[0]-(strict-90)*.02).toFixed(1)+"%";$("relevance").textContent=(base[1]+shifts[1]).toFixed(1)+"%";$("citation").textContent=(base[2]+shifts[2]).toFixed(1)+"%";$("halluc").textContent=Math.max(1.4,base[3]+shifts[3]+(100-strict)*.03).toFixed(1)+"%"}
$("judgeStrict").oninput=evalPrompt;$("promptVersion").onchange=evalPrompt;$("runEval").onclick=evalPrompt;
function causal(){const e=$("estimator").value;$("estimatorLabel").textContent=e;renderEvent()}
$("runCausal").onclick=causal;
const costs=[.10,.15,.21,.30,.40,.50,.75,1.00],values=[1.31,1.26,1.18,1.10,.98,.84,.61,.34];
$("costSensitivity").innerHTML=costs.map((c,i)=>'<div class="bars"><div><span>'+money(c)+'/resolution</span><b style="width:'+Math.round(values[i]/1.31*100)+'%"></b><em>'+money(values[i])+'</em></div></div>').join("");
function policy(){const budget=Number($("trafficBudget").value),effect=Number($("minEffect").value);$("trafficOut").textContent=budget+"%";$("effectOut").textContent=effect.toFixed(1)+" pp";const share=Math.max(0,Math.min(budget,Math.round(74-effect*5)));const value=1.22*(share/68);$("routeShare").textContent=share+"%";$("routeValue").textContent="$"+value.toFixed(2)+"M";$("routeRule").textContent="Route if expected incremental contribution − AI cost > 0 and CATE ≥ "+effect.toFixed(1)+" pp, subject to latency and traffic constraints."; $("routeCostValue").textContent="$"+(0.36*share/68).toFixed(2)+"M";$("economicCoverage").textContent=share+"%"}
$("trafficBudget").oninput=policy;$("minEffect").oninput=policy;renderEvent();policy();evalPrompt();
const traceData=[
{title:"Planner",type:"ORCHESTRATOR",summary:"Converted the business question into a six-stage evaluation workflow.",detail:"Inputs: business brief + experiment context. Outputs: estimand=incremental contribution, eligible population, evaluation plan, required agents. Guardrails: no direct production writes; analysis tools are read-only.",tools:"metric_registry.read · experiment_registry.read · workflow.plan"},
{title:"Product Agent",type:"AI SUPPORT AGENT",summary:"Executed retrieval and tool calls before generating the response.",detail:"Retrieved 2 evidence sets, checked policy eligibility, generated a cited answer and emitted a complete product trace. Tool calls are logged with arguments, latency and result status.",tools:"vector_search · customer_context · policy_lookup · citation_verify · escalation_check · response_generate"},
{title:"Evaluation Agent",type:"EVALUATION AGENT",summary:"Scored 240 traces and calibrated the automated judge.",detail:"Computed faithfulness, relevance, citation correctness and hallucination metrics. Compared judge labels against the human calibration set and routed disagreements to error analysis.",tools:"judge_v3 · calibration_set · bootstrap_ci · disagreement_slice"},
{title:"Causal Agent",type:"CAUSAL ANALYST",summary:"Selected cohort-aware staggered DiD after checking rollout structure.",detail:"Diagnostics: pre-trend review, overlap, cohort timing and outcome stability. Estimated incremental conversion and revenue, then produced an event-study view and robustness notes.",tools:"pretrend_check · did_estimator · event_study · robustness_suite"},
{title:"Causal ML Agent",type:"HETEROGENEITY ANALYST",summary:"Estimated heterogeneous treatment effects with holdout policy evaluation.",detail:"Cross-fitted CATE estimates were evaluated on a held-out population. The agent surfaced lower-value high-cost cases rather than optimizing for treatment probability.",tools:"cross_fit_cate · uplift_curve · policy_value · segment_diagnostics"},
{title:"Policy Agent",type:"ECONOMIC ROUTER",summary:"Converted causal estimates into a constrained routing rule.",detail:"Objective: maximize incremental contribution subject to traffic budget, AI cost, latency SLA and minimum treatment effect. Output: route 68% of eligible traffic; retain an audit trail for every policy decision.",tools:"cost_model · constraint_solver · policy_simulator · rollout_config"}];
function renderTrace(i=0){const d=traceData[i];const el=$("traceDetail");if(!el)return;el.innerHTML='<div class="trace-kicker">'+d.type+'</div><h3>'+d.title+'</h3><p class="trace-summary">'+d.summary+'</p><div class="trace-box"><b>Agent contract</b><p>'+d.detail+'</p></div><div class="trace-tools"><small>TOOLS / ACTIONS</small><code>'+d.tools+'</code></div><div class="trace-meta"><span>model <b>portfolio-agent-v1</b></span><span>tokens <b>'+([412,1280,1840,970,1100,760][i]*10)+'</b></span><span>latency <b>'+([420,2180,1740,1260,1490,1610][i])+'ms</b></span><span>status <b>validated</b></span></div>;}
document.querySelectorAll(".trace-step").forEach(b=>b.onclick=()=>{document.querySelectorAll(".trace-step").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderTrace(Number(b.dataset.trace))});
renderTrace();